version: '3.3'

services:
  pulsar:
    image: "apachepulsar/pulsar:2.7.1"
    command: bin/pulsar standalone
    restart: always
    ports:
      - "6650:6650"
      - "8080:8080"
    volumes:
      - ./pulsar-cfg/data:/pulsar/data
      - ./pulsar-cfg/conf:/pulsar/conf

  pulsar-manager:
    image: "apachepulsar/pulsar-manager:v0.2.0"
    restart: always
    ports:
      - "9527:9527"
      - "7750:7750"
    depends_on:
      - pulsar
    links:
      - pulsar
    environment:
      - SPRING_CONFIGURATION_FILE=/pulsar-manager/pulsar-manager/application.properties
