version: '3.3'

services:
  pulsar:
    image: "apachepulsar/pulsar:2.7.1"
    command: bin/pulsar standalone
    restart: always
    ports:
      - "6650:6650"
      - "8080:8080"
    volumes:
      - ./pulsar-cfg/data:/pulsar/data
      - ./pulsar-cfg/conf:/pulsar/conf

  pulsar-admin:
    image: "windsome/ms-pulsar-admin:1.0.0"
    restart: always
    ports:
      - "3120:3120"
    depends_on:
      - pulsar
    # links:
    #   - pulsar
    volumes:
      - ./admin-cfg:/data/cfg
    environment:
      CFG_PATH: '/data/cfg'
      DEBUG: app:*
    command: ["node", "sdist"]
    # command: ["./wait-for-it.sh", "pulsar:8080", "-s", "-t", "5", "--", "node", "sdist"]
